theme: jekyll-theme-cayman
title: League of Legends Keybind
logo: /assets/img/logo.png
show_downloads: true
github:
  zip_url: https://github.com/iDara09/LeagueOfLegendsKeybind/blob/gh-pages/archive/LoLKeybind.app.zip?raw=true
