theme: jekyll-theme-cayman
title: League of Legends Keybind
logo: /assets/img/logo.png
google_analytics: UA-130183635-1
show_downloads: true
github:
  mac-os-download-url: https://github.com/iDara09/LeagueOfLegendsKeybind/releases/download/v1.0.0/LoLKeybind.zip
  windows-os-download-url: https://idara09.github.io/LeagueOfLegendsKeybind/#faq
